require 'rake'
require 'rspec/core/rake_task'
require_relative 'app/models/users'
require_relative 'app/models/contacts'

require_relative 'config/application'

desc "create the database"
task "db:create" do
  puts "Creating file #{DB_PATH} if it doesn't exist..."
  touch DB_PATH
end

desc "drop the database"
task "db:drop" do
  puts "Deleting #{DB_PATH}..."
  rm_f DB_PATH
end

desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task "db:migrate" do
  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
  end
end

desc "populate the test database with sample data"
task "db:seed" do
  User.create({:username => 'Ed', :password => 'cooldude1', :phone=> "16094548575", :account_sid => "ACe031767d584b6e1828f26021ef460105" , :auth_token=>"b6671160c8e47e88e1573cfbc2e9a258" })
  User.create({:username => 'Will', :password => 'cooldude2', :phone=> "15108621673", :account_sid => "1293123" , :auth_token=>"123123123"})
  Contact.create({:name => 'Will', :number => '15108621673', :user_id => 1})
  Contact.create({:name => 'Ed', :number => '16097517178', :user_id => 2})
  Contact.create({:name => 'Tommy', :number => '7777777777', :user_id => 1})
  Contact.create({:name => 'Nadia', :number => '231231231', :user_id => 1})
  Contact.create({:name => 'Betsy', :number => '1112231123', :user_id => 1})
  Contact.create({:name => 'Strand', :number => '6666666666', :user_id => 2})
end

desc 'Retrieves the current schema version number'
task "db:version" do
  puts "Current version: #{ActiveRecord::Migrator.current_version}"
end

desc 'Start IRB with application environment loaded'
task "console" do
  exec "irb -r./config/application"
end

desc "Run the specs"
RSpec::Core::RakeTask.new(:spec)

task :default  => :specs
